ARG version
FROM almalinux:${version:-9}
ARG course="docker" \
    trainer="sravani" \
    duration="10hrs"
ENV course="docker" \
    trainer="sravani" \
    duration="10hrs"
RUN echo "course is: ${course}, Duration is: ${duration}, trainer is: ${trainer}"