FROM  almalinux:9
ADD https://raw.githubusercontent.com/sravani2019/terraform_devops90s/refs/heads/main/terraform-Devops90s/06-for-loop/README.md /tmp/
CMD ["sleep", "100"]
ADD tar_sample_file_1MB.tar /tmp